camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    authorization:
      enabled: true

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000

#  h2:
#    console:
#      enabled: true
#      path: /console

#server:
#  port: 8081